jwt:
secret: airbnb
server:
  error:
    include-message: always
  port: 5000
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://airbnb.ckmwffwc7ag0.eu-central-1.rds.amazonaws.com:5432/airbnb

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect

  #  sql:
  #    init:
  #      continue-on-error: false
  #      data-locations: classpath:data-initial/data.sql
  #      mode: always
  flyway:
    baseline-on-migrate: true


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: airbnb-bucket

prefix-for-file-link: https://airbnb-bucket.s3.eu-central-1.amazonaws.com/

#google-map
google:
  api-key: ${GOOGLE_API_KEY}





